-- MySql 8;

CREATE TABLE hibernate_sequence (
    NEXT_VAL BIGINT AUTO_INCREMENT,
    PRIMARY KEY (NEXT_VAL)
);
INSERT INTO hibernate_sequence VALUES (0);

CREATE TABLE PIPELINE_RUNS(

    TASK_ID BIGINT NOT NULL,
    RUN_ID BIGINT NOT NULL,

    ORGANIZATION VARCHAR(255) NOT NULL,
    PROJECT VARCHAR(255),
    PIPELINE_ID VARCHAR(255) NOT NULL,
    PIPELINE_NAME VARCHAR(255),

    STATUS VARCHAR(255),
    RESULT VARCHAR(255),
    VARIABLES VARCHAR(5000),
    TEMPLATE_PARAMETERS VARCHAR(5000)

    CREATED_AT TIMESTAMP,
    UPDATED_AT TIMESTAMP,

    PRIMARY KEY (TASKID)

);