-- MySql 8;

-- PIPELINE_RUNS
CREATE TABLE PIPELINE_RUNS(

    TASK_ID BIGINT NOT NULL,
    RUN_ID BIGINT NOT NULL,

    ORGANIZATION VARCHAR(255) NOT NULL,
    PROJECT VARCHAR(255),
    PIPELINE_ID VARCHAR(255) NOT NULL,
    PIPELINE_NAME VARCHAR(255),

    STATUS VARCHAR(255),
    RESULT VARCHAR(255),
    VARIABLES VARCHAR(5000),
    TEMPLATE_PARAMETERS VARCHAR(5000),

    CREATED_AT VARCHAR(255),
    FINISHED_AT VARCHAR(255),

    PRIMARY KEY (TASK_ID)

);