-- MySql 8;

CREATE TABLE hibernate_sequence (
    NEXT_VAL BIGINT AUTO_INCREMENT,
    PRIMARY KEY (NEXT_VAL)
);
INSERT INTO hibernate_sequence VALUES (0);

CREATE TABLE PIPELINE_RUNS(
    TASKID BIGINT NOT NULL AUTO_INCREMENT,

    RUNID BIGINT,
    STATUS VARCHAR(255),

    PRIMARY KEY (TASKID)
);