##########################
# Server configuration
##########################
app:
  workdir:

server:
  port: ${SPRING_PORT}
  error:
    include-message: always
  servlet:
    context-path: /api/v1/up/executor

############################################
# Spring configurations
############################################
spring:
  # Profile
  profile: dev
  # Security
  security:
    oauth2:
      client:
        registration:
          azure-devops:
            authorization-grant-type: client_credentials
            client-id: ${AZURE_ODM_APP_CLIENT_ID}
            client-secret: ${AZURE_ODM_APP_CLIENT_SECRET}
            scope: 499b84ac-1321-427f-aa17-267ca6975798/.default
        provider:
          azure-devops:
            token-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/oauth2/v2.0/token
  jpa:
    hibernate:
      ddl-auto: validate
      #show-sql: true
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        globally_quoted_identifiers: true
        default_schema: ${DATABASE_SCHEMA}
  # DB
  datasource:
    url: ${DATABASE_URL}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED}
      path: /${H2_CONSOLE_PATH}
  # FlyWay configuration
  # More: https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.data-migration
  flyway:
    enabled: true
    url: ${DATABASE_URL}?allowPublicKeyRetrieval=true&useSSL=false
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    #"flyway_schema_history" (i.e., default flyway table) on a different SCHEMA
    schemas: ${DATABASE_SCHEMA}
    locations: classpath:db/migration/${FLYWAY_SCRIPTS_DIR}
    clean-on-validation-error: true