##########################
# Server configuration
##########################
app:
  workdir:

server:
  port: 9003
  error:
    include-message: always
  servlet:
    context-path: /api/v1/up/executor

polling:
  retries: 3
  interval: 10 # Seconds

############################################
# Spring configurations
############################################
spring:
  # Profile
  profile: localmysql
  # Security
  security:
    oauth2:
      client:
        registration:
          azure-devops:
            authorization-grant-type: client_credentials
            client-id: ${AZURE_ODM_APP_CLIENT_ID}
            client-secret: ${AZURE_ODM_APP_CLIENT_SECRET}
            scope: 499b84ac-1321-427f-aa17-267ca6975798/.default
        provider:
          azure-devops:
            token-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID}/oauth2/v2.0/token
            basic-uri: https://dev.azure.com/
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  # DB
  datasource:
    url: jdbc:mysql://localhost:3306/ODMEXECUTOR?useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  h2:
    console:
      enabled: false
  # FlyWay configuration
  # More: https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#appendix.application-properties.data-migration
  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3306/ODMEXECUTOR
    user: "root"
    password: "root"
    #"flyway_schema_history" (i.e., default flyway table) on a different SCHEMA
    #schemas: ODMEXECUTOR  # not working
    locations: classpath:db/migration/mysql
    clean-on-validation-error: true