name: odm-platform-up-services-executor-azuredevops CI
on:
  push:
    branches: # Execute on "main" branch and product branches, avoid others
    - 'main' # Main branch
    - '*.*' # Product branches (e.g., 0.7, 0.7.1, 0.x, 1.1, 1.x, ...)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3.5.2
        with:
          ssh-key: ${{secrets.SSH_KEY}}
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Set env # Extract version and branch from tag and save them as environment variables
        run: echo "BRANCH_NAME=$( echo ${{ github.event.base_ref }} | sed 's|refs/heads/||' )" >> $GITHUB_ENV
      - name: Clone and build odm-platform
        run: |
          git config user.name "github-workflows-cloner"
          git config user.email "<>"
          git clone https://github.com/opendatamesh-initiative/odm-platform.git
          git checkout ${{ env.BRANCH_NAME }}
          cd odm-platform
          mvn -B clean install -DskipTests --file pom.xml
          cd ..
      - name: Build with Maven
        run: mvn clean package spring-boot:repackage -DskipTests
      - name: Execute tests with Maven
        run: mvn -B test -Dspring.profiles.active=dev
